v1 of add iflank

diff --git a/iflank b/iflank
--- a/iflank
+++ b/iflank
@@ -857,12 +857,77 @@ flank_error() {
 	echo '%PAGEEND%'
 }
 
+add_cmd(){
+	# add_cmd <wd> <params>
+	local wd=$1
+	shift
+	if [ -z "$*" ]; then
+		echo 'ERROR: Must specify <scriptname> after `iflank add`'
+		exit 1
+	fi
+	local dir_name="$*"
+	if [ -d "${FLANK_ROOT}/${dir_name}" ]; then
+		suffix_i=2
+		while [ -d "${FLANK_ROOT}/${dir_name}_${suffix_i}" ]; do
+			suffix_i=$((suffix_i + 1))
+		done
+		dir_name="${dir_name}_${suffix_i}"
+		echo 'WARNING: '"$FLANK_ROOT/$*"' already exists. Creating '"$dir_name"
+	fi
+	mkdir "${FLANK_ROOT}/${dir_name}"
+	cat > "${FLANK_ROOT}/${dir_name}/template.sh" << EOF
+# This bash script runs your Python script like you'd run it from the CLI
+
+# ---- Directory -----
+
+# First, it switches to the directory from where you'd run this script
+# This was based on where you ran \`iflank add\`, so you might need to adjust it.
+
+cd $wd
+
+
+# ---- Addtl Setup -----
+
+# Then, you might have a virtual environment that needs to be activated
+# If so, uncomment/tweak the line below by removing the leading "# "
+
+# ./venv/bin/activate
+
+
+# ---- Run Script -----
+
+# Finally it runs your command
+# If your command takes parameters, you'll need to add them below
+# Like if you run \`python myscript.py --year=2015 --mode='fast'\` from the CLI,
+# copy those parameters below.
+# Advanced: You can expose those parameters for user input by making them
+# variables wrapped in \${}, like \`python myscript.py --year=\${year} --mode=\${mode}\`
+
+python $*
+EOF
+	echo ''
+	echo 'Go to http://localhost/'"${dir_name}"
+	echo ''
+}
 help_msg() {
-	printf 'Usage: iflank [run <path>] [--http-mode | -h]\n'
+	printf 'Usage: iflank [run <path>] [add <scriptname>] [--http-mode | -h]\n'
 }
 
 # This traps SIGPIPE, which would get sent if this program tried to write to a broken pipe
 trap "echo 'server disconnected (write pipe)'; exit 1" PIPE
+
+if [ -d /var/lib/flank ]; then
+	FLANK_ROOT=/var/lib/flank
+elif [ -d /opt/homebrew/var/flank ]; then
+	FLANK_ROOT=/opt/homebrew/var/flank
+elif [ -d /usr/local/var/flank ]; then
+	FLANK_ROOT=/usr/local/var/flank
+elif [ -n $(which brew) && $(brew --prefix) >0 ]; then
+	FLANK_ROOT=$(brew --prefix)/var
+else
+	echo "Cannot find flank root!"
+	exit
+fi
 
 while [ "$1" != "" ]; do
 	case $1 in
@@ -877,6 +942,11 @@ while [ "$1" != "" ]; do
 		exit_code=$?
 		exit $exit_code
 		;;
+	add)
+		shift
+		add_cmd "$PWD" "$@"
+		exit
+		;;
 	-h | --help)
 		help_msg
 		exit
@@ -889,18 +959,6 @@ while [ "$1" != "" ]; do
 	shift
 done
 
-if [ -d /var/lib/flank ]; then
-	FLANK_ROOT=/var/lib/flank
-elif [ -d /opt/homebrew/var/flank ]; then
-	FLANK_ROOT=/opt/homebrew/var/flank
-elif [ -d /usr/local/var/flank ]; then
-	FLANK_ROOT=/usr/local/var/flank
-elif [ -n $(which brew) && $(brew --prefix) >0 ]; then
-	FLANK_ROOT=$(brew --prefix)/var
-else
-	echo "Cannot find flank root!"
-	exit
-fi
 PS_VERSION=''
 FIND_VERSION=''
 DATE_VERSION=''
