fkill

diff --git a/iflank b/iflank
--- a/iflank
+++ b/iflank
@@ -463,8 +463,8 @@ safe_cd() {
 	fi
 }
 
-flank_kill() {
-	# flank_kill <run_dir>
+fkill() {
+	# fkill <run_dir>
 	if [ -z "$PS_VERSION" ]; then
 		if [ -n "$(ps --version 2>/dev/null | grep procps)" ]; then
 			PS_VERSION='procps'
@@ -482,7 +482,7 @@ flank_kill() {
 	if [ -n "$kill_pid" ]; then
 		kill "$kill_pid"
 	else
-		echo "ERROR: could not find PID for flank_kill ${1}" 1>&2
+		echo "ERROR: could not find PID for fkill ${1}" 1>&2
 	fi
 }
 
@@ -1082,7 +1082,7 @@ log_dir() {
 		disabled_class='class="disabled"'
 	fi
 	echo '<div id="pFooter">'
-	echo '<a '"$disabled_class"' onclick="run('\''kill '"$PWD"\'')">Kill</a>'
+	echo '<a '"$disabled_class"' onclick="run('\''fkill '"$PWD"\'')">Kill</a>'
 	echo '<a '"$disabled_class"' onclick="run('\''fcat exec.sh'\'')">View exec.sh</a>'
 	disabled_class=''
 	path_components=(${PWD//\// })
@@ -1556,19 +1556,11 @@ while true; do
 		# add_cron <dir> <k=v&k=v>
 		# everything after first space, then space delimited
 		split_kvs=$(echo "${args#* }" | tr '&' ' ')
-		echo "split kvs" 1>&2
-		echo "$split_kvs" 1>&2
 		first_kv="${split_kvs%% *}"
-		echo "first_kv" 1>&2
-		echo "$first_kv" 1>&2
 		first_value="${first_kv#*=}"
-		echo "first_value" 1>&2
-		echo "$first_value" 1>&2
 		cron_expr=$(printf '%b' "$(sed 's/+/ /g; s/%/\\x/g' <<<${first_value})")
 		rest_kvs="${split_kvs#* }"
 		new_cron_line="$cron_expr $(which iflank) run ${PWD}/template.sh $rest_kvs"
-		echo "new_cron_line" 1>&2
-		echo "$new_cron_line" 1>&2
 		(
 			crontab -l 2>/dev/null
 			echo "$new_cron_line"
@@ -1581,8 +1573,8 @@ while true; do
 	fmkdir)
 		fmkdir "$args"
 		;;
-	kill)
-		flank_kill "$args"
+	fkill)
+		fkill "$args"
 		;;
 	*)
 		read -rp "Invalid choice! Hit [Enter] to continue" || readerr
