rework loop

diff --git a/iflank b/iflank
--- a/iflank
+++ b/iflank
@@ -360,7 +360,7 @@ readerr() {
 	exit 1
 }
 
-PAGE='HTTP_INIT'
+PAGE='HOME'
 
 help_msg() {
 	printf 'Usage: iflank [run <path>] [--http-mode | -h]\n'
@@ -399,19 +399,91 @@ TIME_VERSION=''
 
 cd $FLANK_ROOT
 while true; do
-	case "$PAGE" in
-	HTTP_INIT)
-		read -r choice || readerr
-		case $choice in
-		refresh)
-			PAGE='HOME'
-			;;
-		*)
-			echo "ERROR: Invalid input to HTTP_INIT: $choice" 1>&2
-			PAGE='HOME'
-			;;
-		esac
+	read -r choice args || readerr
+	active_pid=$(cat "$active_pid_file")
+	if [ -n "$active_pid" ]; then
+		kill_tree "$active_pid"
+		active_pid_file=''
+	fi
+	case $choice in
+	cd)
+		safe_cd $args
 		;;
+	history)
+		PAGE='HISTORY'
+		;;
+	refresh)
+		;;
+	run)
+		if [ "${args%% *}" == '.' ]; then
+			split_kvs=$(echo "${args#* }" | tr '&' ' ')
+			cmd_run_dir=$(run_cmd 'bg' '.' $split_kvs)
+			safe_cd "$cmd_run_dir"
+		else
+			echo 'Must run this command via "run ."'
+		fi
+		;;
+	savefile)
+		if [ "${arg%% *}" == '.' ]; then
+			split_kvs=$(echo "${arg#* }" | tr '&' ' ')
+			file_contents="${arg#*=}"
+			echo "file contents" 1>&2
+			echo "$file_contents" 1>&2
+			cleaned_file=$(printf '%b' "$(sed 's/+/ /g; s/%/\\x/g' <<<${file_contents})")
+			echo "cleaned file" 1>&2
+			echo "$cleaned_file" 1>&2
+			cat <<<"$cleaned_file" >template.sh
+		fi
+
+		PAGE='CMD'
+
+		;;
+	crontab)
+		PAGE='CRONTAB'
+		;;
+	editfileform)
+		PAGE='EDITFILEFORM'
+		;;
+	createcronform)
+		PAGE='CREATECRONFORM'
+		;;
+	createcron)
+		if [ "${args%% *}" == '.' ]; then
+			split_kvs=$(echo "${args#* }" | tr '&' ' ')
+			echo "split kvs" 1>&2
+			echo "$split_kvs" 1>&2
+			url_encoded="${split_kvs#*=}"
+			cleaned_expr=$(printf '%b' "$(sed 's/+/ /g; s/%/\\x/g' <<<${url_encoded})")
+			cron="$cleaned_expr iflank run ${PWD}/template.sh"
+			echo "cron" 1>&2
+			echo "$cron" 1>&2
+			(
+				crontab -l 2>/dev/null
+				echo "$cron"
+			) | crontab -
+		fi
+		PAGE='CRONTAB'
+		;;
+	kill)
+		kill $pid
+		;;
+	*)
+		read -rp "Invalid choice! Hit [Enter] to continue" || readerr
+		;;
+	esac
+	case "$PAGE" in
+	# HTTP_INIT)
+	# 	read -r choice || readerr
+	# 	case $choice in
+	# 	refresh)
+	# 		PAGE='HOME'
+	# 		;;
+	# 	*)
+	# 		echo "ERROR: Invalid input to HTTP_INIT: $choice" 1>&2
+	# 		PAGE='HOME'
+	# 		;;
+	# 	esac
+	# 	;;
 	HOME)
 		echo '%PAGESTART%'
 		header_pwd
@@ -424,19 +496,19 @@ while true; do
 		echo '</div>'
 		echo '<div id="pFooter"></div>'
 		echo '%PAGEEND%'
-		read -r choice args || readerr
-		case $choice in
-		cd)
-			safe_cd $args
-			;;
-		history)
-			PAGE='HISTORY'
-			;;
-		refresh) ;;
-		*)
-			read -rp "Invalid choice! Hit [Enter] to continue" || readerr
-			;;
-		esac
+		# read -r choice args || readerr
+		# case $choice in
+		# cd)
+		# 	safe_cd $args
+		# 	;;
+		# history)
+		# 	PAGE='HISTORY'
+		# 	;;
+		# refresh) ;;
+		# *)
+		# 	read -rp "Invalid choice! Hit [Enter] to continue" || readerr
+		# 	;;
+		# esac
 		;;
 	HISTORY)
 		echo '%PAGESTART%'
@@ -473,7 +545,7 @@ while true; do
 		echo %TABLEHEADEND%
 
 		echo %APPENDTRSTART%
-		history_pid_file=$(mktemp)
+		active_pid_file=$(mktemp)
 		if [ "$FIND_VERSION" == 'gnu' ]; then
 			regex_flag='-regextype posix-extended'
 			extended_flag=''
@@ -492,27 +564,27 @@ while true; do
 				xargs awk -v OFS='\t' -v PS_VERSION=$PS_VERSION -v DATE_VERSION=$DATE_VERSION "$awk_columns" |
 				awk $awk_flag -v FS='\t' "$awk_tsv_to_html" && echo '%APPENDTREND%' &
 			pid=$!
-			echo "$pid" >$history_pid_file
+			echo "$pid" >$active_pid_file
 			wait "$pid"
-			: >$history_pid_file
+			: >$active_pid_file
 		} &
-		read -r choice args || readerr
-		history_pid=$(cat $history_pid_file)
-		if [ -n "$history_pid" ]; then
-			kill_tree "$history_pid"
-		fi
-		case $choice in
-		cd)
-			safe_cd $args
-			;;
-		history)
-			PAGE='HISTORY'
-			;;
-		refresh) ;;
-		*)
-			read -rp "Invalid choice! Hit [Enter] to continue" || readerr
-			;;
-		esac
+		# read -r choice args || readerr
+		# active_pid=$(cat $active_pid_file)
+		# if [ -n "$active_pid" ]; then
+		# 	kill_tree "$active_pid"
+		# fi
+		# case $choice in
+		# cd)
+		# 	safe_cd $args
+		# 	;;
+		# history)
+		# 	PAGE='HISTORY'
+		# 	;;
+		# refresh) ;;
+		# *)
+		# 	read -rp "Invalid choice! Hit [Enter] to continue" || readerr
+		# 	;;
+		# esac
 		;;
 	FS)
 		echo '%PAGESTART%'
@@ -523,19 +595,19 @@ while true; do
 		echo '</div>'
 		echo '<div id="pFooter"></div>'
 		echo '%PAGEEND%'
-		read -r choice arg || readerr
-		case $choice in
-		cd)
-			safe_cd $arg
-			;;
-		history)
-			PAGE='HISTORY'
-			;;
-		refresh) ;;
-		*)
-			read -rp "Invalid choice! Hit [Enter] to continue" || readerr
-			;;
-		esac
+		# read -r choice arg || readerr
+		# case $choice in
+		# cd)
+		# 	safe_cd $arg
+		# 	;;
+		# history)
+		# 	PAGE='HISTORY'
+		# 	;;
+		# refresh) ;;
+		# *)
+		# 	read -rp "Invalid choice! Hit [Enter] to continue" || readerr
+		# 	;;
+		# esac
 		;;
 	CMD)
 		echo '%PAGESTART%'
@@ -553,34 +625,34 @@ while true; do
 		echo '<a onclick="run('\''crontab'\'')">Cron</a>'
 		echo '</div>'
 		echo '%PAGEEND%'
-		read -r choice args || readerr
-		case $choice in
-		run)
-			if [ "${args%% *}" == '.' ]; then
-				split_kvs=$(echo "${args#* }" | tr '&' ' ')
-				cmd_run_dir=$(run_cmd 'bg' '.' $split_kvs)
-				safe_cd "$cmd_run_dir"
-			else
-				echo 'Must run this command via "run ."'
-			fi
-			;;
-		cd)
-			safe_cd "${args[0]}"
-			;;
-		crontab)
-			PAGE='CRONTAB'
-			;;
-		editfileform)
-			PAGE='EDITFILEFORM'
-			;;
-		history)
-			PAGE='HISTORY'
-			;;
-		refresh) ;;
-		*)
-			read -rp "Invalid choice! Hit [Enter] to continue" || readerr
-			;;
-		esac
+		# read -r choice args || readerr
+		# case $choice in
+		# run)
+		# 	if [ "${args%% *}" == '.' ]; then
+		# 		split_kvs=$(echo "${args#* }" | tr '&' ' ')
+		# 		cmd_run_dir=$(run_cmd 'bg' '.' $split_kvs)
+		# 		safe_cd "$cmd_run_dir"
+		# 	else
+		# 		echo 'Must run this command via "run ."'
+		# 	fi
+		# 	;;
+		# cd)
+		# 	safe_cd "${args[0]}"
+		# 	;;
+		# crontab)
+		# 	PAGE='CRONTAB'
+		# 	;;
+		# editfileform)
+		# 	PAGE='EDITFILEFORM'
+		# 	;;
+		# history)
+		# 	PAGE='HISTORY'
+		# 	;;
+		# refresh) ;;
+		# *)
+		# 	read -rp "Invalid choice! Hit [Enter] to continue" || readerr
+		# 	;;
+		# esac
 		;;
 	EDITFILEFORM)
 		echo '%PAGESTART%'
@@ -608,34 +680,34 @@ while true; do
 		echo '<a onclick="run('\''history'\'')">Logs</a>'
 		echo '</div>'
 		echo '%PAGEEND%'
-		read -r choice arg || readerr
-		case $choice in
-		savefile)
-			if [ "${arg%% *}" == '.' ]; then
-				split_kvs=$(echo "${arg#* }" | tr '&' ' ')
-				file_contents="${arg#*=}"
-				echo "file contents" 1>&2
-				echo "$file_contents" 1>&2
-				cleaned_file=$(printf '%b' "$(sed 's/+/ /g; s/%/\\x/g' <<<${file_contents})")
-				echo "cleaned file" 1>&2
-				echo "$cleaned_file" 1>&2
-				cat <<<"$cleaned_file" >template.sh
-			fi
+		# read -r choice arg || readerr
+		# case $choice in
+		# savefile)
+		# 	if [ "${arg%% *}" == '.' ]; then
+		# 		split_kvs=$(echo "${arg#* }" | tr '&' ' ')
+		# 		file_contents="${arg#*=}"
+		# 		echo "file contents" 1>&2
+		# 		echo "$file_contents" 1>&2
+		# 		cleaned_file=$(printf '%b' "$(sed 's/+/ /g; s/%/\\x/g' <<<${file_contents})")
+		# 		echo "cleaned file" 1>&2
+		# 		echo "$cleaned_file" 1>&2
+		# 		cat <<<"$cleaned_file" >template.sh
+		# 	fi
 
-			PAGE='CMD'
+		# 	PAGE='CMD'
 
-			;;
-		cd)
-			safe_cd "${args[0]}"
-			;;
-		history)
-			PAGE='HISTORY'
-			;;
-		refresh) ;;
-		*)
-			read -rp "Invalid choice! Hit [Enter] to continue" || readerr
-			;;
-		esac
+		# 	;;
+		# cd)
+		# 	safe_cd "${args[0]}"
+		# 	;;
+		# history)
+		# 	PAGE='HISTORY'
+		# 	;;
+		# refresh) ;;
+		# *)
+		# 	read -rp "Invalid choice! Hit [Enter] to continue" || readerr
+		# 	;;
+		# esac
 		;;
 	CRONTAB)
 		echo '%PAGESTART%'
@@ -648,22 +720,22 @@ while true; do
 		echo '<a onclick="run('\''history'\'')">Logs</a>'
 		echo '</div>'
 		echo '%PAGEEND%'
-		read -r choice args || readerr
-		case $choice in
-		cd)
-			safe_cd $arg
-			;;
-		createcronform)
-			PAGE='CREATECRONFORM'
-			;;
-		history)
-			PAGE='HISTORY'
-			;;
-		refresh) ;;
-		*)
-			read -rp "Invalid choice! Hit [Enter] to continue" || readerr
-			;;
-		esac
+		# read -r choice args || readerr
+		# case $choice in
+		# cd)
+		# 	safe_cd $arg
+		# 	;;
+		# createcronform)
+		# 	PAGE='CREATECRONFORM'
+		# 	;;
+		# history)
+		# 	PAGE='HISTORY'
+		# 	;;
+		# refresh) ;;
+		# *)
+		# 	read -rp "Invalid choice! Hit [Enter] to continue" || readerr
+		# 	;;
+		# esac
 		;;
 	CREATECRONFORM)
 		echo '%PAGESTART%'
@@ -678,38 +750,38 @@ while true; do
 		echo '<a onclick="run('\''history'\'')">Logs</a>'
 		echo '</div>'
 		echo '%PAGEEND%'
-		read -r choice args || readerr
-		echo "cron expression" 1>&2
-		echo "$args" 1>&2
-		case $choice in
-		createcron)
-			if [ "${args%% *}" == '.' ]; then
-				split_kvs=$(echo "${args#* }" | tr '&' ' ')
-				echo "split kvs" 1>&2
-				echo "$split_kvs" 1>&2
-				url_encoded="${split_kvs#*=}"
-				cleaned_expr=$(printf '%b' "$(sed 's/+/ /g; s/%/\\x/g' <<<${url_encoded})")
-				cron="$cleaned_expr iflank run ${PWD}/template.sh"
-				echo "cron" 1>&2
-				echo "$cron" 1>&2
-				(
-					crontab -l 2>/dev/null
-					echo "$cron"
-				) | crontab -
-			fi
-			PAGE='CRONTAB'
-			;;
-		cd)
-			safe_cd $arg
-			;;
-		history)
-			PAGE='HISTORY'
-			;;
-		refresh) ;;
-		*)
-			read -rp "Invalid choice! Hit [Enter] to continue" || readerr
-			;;
-		esac
+		# read -r choice args || readerr
+		# echo "cron expression" 1>&2
+		# echo "$args" 1>&2
+		# case $choice in
+		# createcron)
+		# 	if [ "${args%% *}" == '.' ]; then
+		# 		split_kvs=$(echo "${args#* }" | tr '&' ' ')
+		# 		echo "split kvs" 1>&2
+		# 		echo "$split_kvs" 1>&2
+		# 		url_encoded="${split_kvs#*=}"
+		# 		cleaned_expr=$(printf '%b' "$(sed 's/+/ /g; s/%/\\x/g' <<<${url_encoded})")
+		# 		cron="$cleaned_expr iflank run ${PWD}/template.sh"
+		# 		echo "cron" 1>&2
+		# 		echo "$cron" 1>&2
+		# 		(
+		# 			crontab -l 2>/dev/null
+		# 			echo "$cron"
+		# 		) | crontab -
+		# 	fi
+		# 	PAGE='CRONTAB'
+		# 	;;
+		# cd)
+		# 	safe_cd $arg
+		# 	;;
+		# history)
+		# 	PAGE='HISTORY'
+		# 	;;
+		# refresh) ;;
+		# *)
+		# 	read -rp "Invalid choice! Hit [Enter] to continue" || readerr
+		# 	;;
+		# esac
 		;;
 	LOG_DIR)
 		echo '%PAGESTART%'
@@ -751,7 +823,7 @@ while true; do
 
 		# Write the PID to a file so that the background job running `tail -f`
 		# can mutate it (set it to '' once the process finishes)
-		tail_pid_file=$(mktemp)
+		active_pid_file=$(mktemp)
 		if [ "$state" == 'after' ]; then
 			echo '%APPENDPAGEBODYSTART%'
 			cat console.log
@@ -762,31 +834,31 @@ while true; do
 				echo '%STREAMPAGEBODYSTART%'
 				tail -f -n +1 console.log &
 				pid=$!
-				echo "$pid" >$tail_pid_file
+				echo "$pid" >$active_pid_file
 				wait "$pid"
-				: >$tail_pid_file
+				: >$active_pid_file
 			} &
 		fi
-		read -r choice args || readerr
-		tail_pid=$(cat $tail_pid_file)
-		if [ -n "$tail_pid" ]; then
-			kill_tree "$tail_pid"
-		fi
-		case $choice in
-		kill)
-			kill $pid
-			;;
-		cd)
-			safe_cd $args
-			;;
-		history)
-			PAGE='HISTORY'
-			;;
-		refresh) ;;
-		*)
-			read -rp "Invalid choice! Hit [Enter] to continue" || readerr
-			;;
-		esac
+		# read -r choice args || readerr
+		# active_pid=$(cat $active_pid_file)
+		# if [ -n "$active_pid" ]; then
+		# 	kill_tree "$active_pid"
+		# fi
+		# case $choice in
+		# kill)
+		# 	kill $pid
+		# 	;;
+		# cd)
+		# 	safe_cd $args
+		# 	;;
+		# history)
+		# 	PAGE='HISTORY'
+		# 	;;
+		# refresh) ;;
+		# *)
+		# 	read -rp "Invalid choice! Hit [Enter] to continue" || readerr
+		# 	;;
+		# esac
 		;;
 	*)
 		echo '%PAGESTART%'
