add run()

diff --git a/iflank b/iflank
--- a/iflank
+++ b/iflank
@@ -1,5 +1,32 @@
 #!/usr/bin/env bash
 
+function run() {
+
+    local datetime=$(date '+%Y-%m-%dT%Hh%Mm%Ss')
+    local flogdatedir=$(pwd)/runs/$(echo $datetime | cut -c -10)
+    mkdir -p $flogdatedir
+    local flogdir=$(pwd)/runs/$(echo $datetime | cut -c -10)/$(echo $datetime | cut -c 12-17)
+    if ! mkdir $flogdir 2> /dev/null; then
+	# include seconds
+	flogdir=$(pwd)/runs/$(echo $datetime | cut -c -10)/$(echo $datetime | cut -c 12-20)
+	if ! mkdir $flogdir 2> /dev/null; then
+	    local i=2
+	    local flogdir_base=$flogdir
+	    flogdir=$flogdir_base'_'$i
+	    until mkdir $flogdir 2> /dev/null ; do
+		i=$(($i + 1))
+		flogdir=$flogdir_base'_'$i
+	    done
+	fi
+    fi
+    cp template.sh $flogdir/exec.sh
+
+    # Subtle quoting things:
+    #  - $? needs to be escaped as \$? in "" or it will immediately evaluate
+    #  - $(date) needs to be single quoted or it will immediately evaluate
+    #  - $? needs to be evaluated before $(date) or it will return the exit code of $(date)
+    nohup bash -c "printf 'StartTime:\t%s\n' "'$(date "+%s")'" > $flogdir/status; bash $flogdir/exec.sh 1> $flogdir/stdout.log 2> $flogdir/stderr.log ; printf 'ExitCode:\t%d\nEndTime:\t%d\n' \$? "'$(date "+%s")'" >> $flogdir/status" &
+}
 PAGE='HOME'
 PROMPT='iflank> '
 if [ -d /var/lib/flank ]; then
